title:               Deepesh Toshniwal
url:                 https://dtoshniwal.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Deepesh Toshniwal
  url:               dtoshniwal.github.io
  email:             d.toshniwal@tudelft.nl

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
